# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake/bin/cmake

# The command to remove a file.
RM = /opt/cmake/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/game-rogue-sdl/game-rogue-sdl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/game-rogue-sdl/game-rogue-sdl/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/game-rogue-sdl/game-rogue-sdl/build/CMakeFiles /home/runner/work/game-rogue-sdl/game-rogue-sdl/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/game-rogue-sdl/game-rogue-sdl/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/Classes/DataTypes/Vector2D.o: src/Classes/DataTypes/Vector2D.cpp.o

.PHONY : src/Classes/DataTypes/Vector2D.o

# target to build an object file
src/Classes/DataTypes/Vector2D.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Classes/DataTypes/Vector2D.cpp.o
.PHONY : src/Classes/DataTypes/Vector2D.cpp.o

src/Classes/DataTypes/Vector2D.i: src/Classes/DataTypes/Vector2D.cpp.i

.PHONY : src/Classes/DataTypes/Vector2D.i

# target to preprocess a source file
src/Classes/DataTypes/Vector2D.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Classes/DataTypes/Vector2D.cpp.i
.PHONY : src/Classes/DataTypes/Vector2D.cpp.i

src/Classes/DataTypes/Vector2D.s: src/Classes/DataTypes/Vector2D.cpp.s

.PHONY : src/Classes/DataTypes/Vector2D.s

# target to generate assembly for a file
src/Classes/DataTypes/Vector2D.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Classes/DataTypes/Vector2D.cpp.s
.PHONY : src/Classes/DataTypes/Vector2D.cpp.s

src/Classes/ECS/Collision.o: src/Classes/ECS/Collision.cpp.o

.PHONY : src/Classes/ECS/Collision.o

# target to build an object file
src/Classes/ECS/Collision.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Classes/ECS/Collision.cpp.o
.PHONY : src/Classes/ECS/Collision.cpp.o

src/Classes/ECS/Collision.i: src/Classes/ECS/Collision.cpp.i

.PHONY : src/Classes/ECS/Collision.i

# target to preprocess a source file
src/Classes/ECS/Collision.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Classes/ECS/Collision.cpp.i
.PHONY : src/Classes/ECS/Collision.cpp.i

src/Classes/ECS/Collision.s: src/Classes/ECS/Collision.cpp.s

.PHONY : src/Classes/ECS/Collision.s

# target to generate assembly for a file
src/Classes/ECS/Collision.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Classes/ECS/Collision.cpp.s
.PHONY : src/Classes/ECS/Collision.cpp.s

src/Classes/ECS/ECS.o: src/Classes/ECS/ECS.cpp.o

.PHONY : src/Classes/ECS/ECS.o

# target to build an object file
src/Classes/ECS/ECS.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Classes/ECS/ECS.cpp.o
.PHONY : src/Classes/ECS/ECS.cpp.o

src/Classes/ECS/ECS.i: src/Classes/ECS/ECS.cpp.i

.PHONY : src/Classes/ECS/ECS.i

# target to preprocess a source file
src/Classes/ECS/ECS.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Classes/ECS/ECS.cpp.i
.PHONY : src/Classes/ECS/ECS.cpp.i

src/Classes/ECS/ECS.s: src/Classes/ECS/ECS.cpp.s

.PHONY : src/Classes/ECS/ECS.s

# target to generate assembly for a file
src/Classes/ECS/ECS.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Classes/ECS/ECS.cpp.s
.PHONY : src/Classes/ECS/ECS.cpp.s

src/Classes/Game.o: src/Classes/Game.cpp.o

.PHONY : src/Classes/Game.o

# target to build an object file
src/Classes/Game.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Classes/Game.cpp.o
.PHONY : src/Classes/Game.cpp.o

src/Classes/Game.i: src/Classes/Game.cpp.i

.PHONY : src/Classes/Game.i

# target to preprocess a source file
src/Classes/Game.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Classes/Game.cpp.i
.PHONY : src/Classes/Game.cpp.i

src/Classes/Game.s: src/Classes/Game.cpp.s

.PHONY : src/Classes/Game.s

# target to generate assembly for a file
src/Classes/Game.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Classes/Game.cpp.s
.PHONY : src/Classes/Game.cpp.s

src/Classes/TextureManager.o: src/Classes/TextureManager.cpp.o

.PHONY : src/Classes/TextureManager.o

# target to build an object file
src/Classes/TextureManager.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Classes/TextureManager.cpp.o
.PHONY : src/Classes/TextureManager.cpp.o

src/Classes/TextureManager.i: src/Classes/TextureManager.cpp.i

.PHONY : src/Classes/TextureManager.i

# target to preprocess a source file
src/Classes/TextureManager.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Classes/TextureManager.cpp.i
.PHONY : src/Classes/TextureManager.cpp.i

src/Classes/TextureManager.s: src/Classes/TextureManager.cpp.s

.PHONY : src/Classes/TextureManager.s

# target to generate assembly for a file
src/Classes/TextureManager.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Classes/TextureManager.cpp.s
.PHONY : src/Classes/TextureManager.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... src/Classes/DataTypes/Vector2D.o"
	@echo "... src/Classes/DataTypes/Vector2D.i"
	@echo "... src/Classes/DataTypes/Vector2D.s"
	@echo "... src/Classes/ECS/Collision.o"
	@echo "... src/Classes/ECS/Collision.i"
	@echo "... src/Classes/ECS/Collision.s"
	@echo "... src/Classes/ECS/ECS.o"
	@echo "... src/Classes/ECS/ECS.i"
	@echo "... src/Classes/ECS/ECS.s"
	@echo "... src/Classes/Game.o"
	@echo "... src/Classes/Game.i"
	@echo "... src/Classes/Game.s"
	@echo "... src/Classes/TextureManager.o"
	@echo "... src/Classes/TextureManager.i"
	@echo "... src/Classes/TextureManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

